### ISSUE TITLE
UltraNest support

### ISSUE THREAD

**Issue by JohannesBuchner** [briandigiorgio/NIRVANA#15]
Would you be interested to add support for https://johannesbuchner.github.io/UltraNest/ ?
The interface should be very similar to dynesty.
UltraNest is a very reliable tuning-parameter-free algorithm. It can be faster than dynesty, especially if you take advantage of vectorization.
It also supports resuming from disk and MPI parallelisation, if that is useful to you.

**Comment by briandigiorgio** [comment]
Hi Johannes,
After reading through the documentation, I implemented basic support for UltraNest into our existing fitting program with a stepsampler. I didn't see any speed gains compared to dynesty (in fact I think it is slower). This is probably due to the fact that we have around 25-50 parameters with strong degeneracies between them and a likelihood function that is impossible to vectorize the likelihood function. Still, I enjoyed the cool interface for monitoring the posteriors in real time.

I don't know if you're looking for feedback, but if you want to improve compatibility with dynesty (which already is pretty great), I would recommend adding the ability to feed arguments to the log likelihood and prior transform from the sampler. I had to redefine my functions so they could work without arguments.

**Comment by JohannesBuchner** [comment]
Ah, very interesting. Could you share a bit more information about the dynesty/ultranest comparison?
How many nested sampling iterations, how many live points, how many slice sampler steps per iteration?
Thanks for trying and the feedback.
